print('There once was a movie star icon')
print('who preferred to sleep with the light on')
print('They learned how to code')
print('a device that sure glowed')
print('and lit up the night using Python!')
